services:
  app:
    container_name: sendme-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    networks:
      - sendme-net
  db:
    container_name: sendme-db
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: sendme
    ports:
      - "5436:5432"
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - sendme-net

  redis:
    image: redis:alpine
    container_name: sendme-redis
    ports:
      - '6380:6379'
    restart: always
    command: redis-server --appendonly yes
    networks:
      - sendme-net

volumes:
  db-data:


networks:
  sendme-net:
