services:
  app:
    container_name: app
    image: bacca2095/backend:latest
    environment:
      NODE_ENV: "development"
      DATABASE_URL: "postgres://root:pass@db/finance?schema=public"
      JWT_SECRET: "as"
      PORT: 3001
      OPENSEARCH_URL: "http://opensearch:9200"
      CONTABO_CLIENT_ID: "INT-13560647"
      CONTABO_CLIENT_SECRET: "d8mxvDaSZ0bhwvtvpF24MflDEVlh97ch"
      CONTABO_API_USER: "bacca2095@gmail.com"
      CONTABO_API_PASSWORD: "Hk1xMHR@e&116U"
      CONTABO_AUTH_URL: "https://auth.contabo.com/auth/realms/contabo/protocol/openid-connect/token"
      CONTABO_API_URL: "https://api.contabo.com/v1"
      CONTABO_DEFAULT_SSH_ID: 127347
    restart: always
    ports:
      - "3001:3001"
    networks:
      - opensearch-net
  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: finance
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - opensearch-net

  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - DEBUG=${DEBUG:-0}
    volumes:
      - localstack-data:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always
    networks:
      - opensearch-net

  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node
      - discovery.seed_hosts=opensearch-node
      - cluster.initial_cluster_manager_nodes=opensearch-node
      - bootstrap.memory_lock=true
      - 'OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m'
      - 'DISABLE_INSTALL_DEMO_CONFIG=true'
      - 'DISABLE_SECURITY_PLUGIN=true'
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - opensearch-net
    restart: always

  dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: dashboards
    ports:
      - "5601:5601"
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
      - 'DISABLE_SECURITY_DASHBOARDS_PLUGIN=true'
    restart: always
    networks:
      - opensearch-net

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  db-data:
  localstack-data:
  opensearch-data:


networks:
  opensearch-net:
