services:
  db:
    container_name: sendme-db
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: sendme
    ports:
      - "5436:5432"
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - sendme-net

  redis:
    container_name: sendme-redis
    image: redis:alpine
    ports:
      - '6379:6379'
    restart: unless-stopped
    command: redis-server --appendonly yes

  opensearch-node:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node
      - discovery.seed_hosts=opensearch-node
      - cluster.initial_cluster_manager_nodes=opensearch-node
      - bootstrap.memory_lock=true
      - 'OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m'
      - 'DISABLE_INSTALL_DEMO_CONFIG=true'
      - 'DISABLE_SECURITY_PLUGIN=true'
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - 9201:9200
      - 9601:9600
    networks:
      - sendme-net
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5602:5601
    expose:
      - '5602'
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch-node:9200"]'
      - 'DISABLE_SECURITY_DASHBOARDS_PLUGIN=true'
    networks:
      - sendme-net

volumes:
  db-data:
  opensearch-data:


networks:
  sendme-net:
