services:
  db:
    container_name: sendme-db
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: sendme
    ports:
      - "5436:5432"
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - sendme-net

  redis:
    container_name: sendme-redis
    image: redis:alpine
    ports:
      - '6379:6379'
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  db-data:


networks:
  sendme-net:
